### ISSUE TITLE
TypeError when using corrplot

### ISSUE THREAD

**Issue by shakedzy** [drazenz/heatmap#5]
Hi,
I can't seem to plot a `corrplot`. Here's what I'm running:

```python
>>> import pandas as pd
>>> from sklearn import datasets
>>> from heatmap import corrplot
>>> iris = datasets.load_iris()
>>> X = pd.DataFrame(data=iris.data, columns=iris.feature_names)
>>> y = pd.DataFrame(data=iris.target, columns=['target'])
>>> df = pd.concat([X, y], axis=1)
>>> corrplot(df.corr())
```

I get:
```
Traceback (most recent call last):
  File "/Users/shaked.z/myenv/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shaked.z/myenv/lib/python3.6/site-packages/heatmap/heatmap.py", line 129, in corrplot
    palette=sns.diverging_palette(20, 220, n=256),
  File "/Users/shaked.z/myenv/lib/python3.6/site-packages/seaborn/palettes.py", line 694, in diverging_palette
    neg = palfunc((h_neg, s, l), 128 - (sep / 2), reverse=True, input="husl")
  File "/Users/shaked.z/myenv/lib/python3.6/site-packages/seaborn/palettes.py", line 591, in light_palette
    return blend_palette(colors, n_colors, as_cmap)
  File "/Users/shaked.z/myenv/lib/python3.6/site-packages/seaborn/palettes.py", line 727, in blend_palette
    pal = _ColorPalette(pal(np.linspace(0, 1, n_colors)))
  File "<__array_function__ internals>", line 6, in linspace
  File "/Users/shaked.z/myenv/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```

Installed heatmapz 0.0.4 using pip. Thanks!

**Comment by drazenz** [comment]
Hey @shakedzy it looks like the error is with seaborn and numpy. 

Note that right after `palette=sns.diverging_palette(20, 220, n=256)` the stack trace goes into  seaborn lib.

However, I managed to run it the the first time I tried, so I'm suspecting it might be due to package versions you're using.

I'm running python 3.7.4 and here are pip versions I'm using:
```
matplotlib==3.2.1
numpy==1.17.4
pandas==0.25.3
pyasn1==0.4.8
scikit-learn==0.22.2.post1
scipy==1.4.1
seaborn==0.10.0

```

Can you send me the versions of `seaborn` and `numpy` in your virtualenv, I want to make sure I'm using `seaborn.diverging_palette` correctly.

Also let me know if updating the packages solves it for you.

Cheers!

**Comment by shakedzy** [comment]
I was using `seaborn==0.8.1`, upgraded to `0.10.0` and it solved it. Thanks!
